/* GtkSinticBolivia.h generated by valac 0.54.7, the Vala compiler, do not modify */

#ifndef __GTKSINTICBOLIVIA_H__
#define __GTKSINTICBOLIVIA_H__

#include <gtk/gtk.h>
#include <glib-object.h>
#include <SinticBolivia.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <cairo-gobject.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define SINTIC_BOLIVIA_GTK_TYPE_DB_TABLE_TREE_VIEW (sintic_bolivia_gtk_db_table_tree_view_get_type ())
#define SINTIC_BOLIVIA_GTK_DB_TABLE_TREE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_DB_TABLE_TREE_VIEW, SinticBoliviaGtkDbTableTreeView))
#define SINTIC_BOLIVIA_GTK_DB_TABLE_TREE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_DB_TABLE_TREE_VIEW, SinticBoliviaGtkDbTableTreeViewClass))
#define SINTIC_BOLIVIA_GTK_IS_DB_TABLE_TREE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_DB_TABLE_TREE_VIEW))
#define SINTIC_BOLIVIA_GTK_IS_DB_TABLE_TREE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_DB_TABLE_TREE_VIEW))
#define SINTIC_BOLIVIA_GTK_DB_TABLE_TREE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_DB_TABLE_TREE_VIEW, SinticBoliviaGtkDbTableTreeViewClass))

typedef struct _SinticBoliviaGtkDbTableTreeView SinticBoliviaGtkDbTableTreeView;
typedef struct _SinticBoliviaGtkDbTableTreeViewClass SinticBoliviaGtkDbTableTreeViewClass;
typedef struct _SinticBoliviaGtkDbTableTreeViewPrivate SinticBoliviaGtkDbTableTreeViewPrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_SB_FIXED (sintic_bolivia_gtk_sb_fixed_get_type ())
#define SINTIC_BOLIVIA_GTK_SB_FIXED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_FIXED, SinticBoliviaGtkSBFixed))
#define SINTIC_BOLIVIA_GTK_SB_FIXED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_FIXED, SinticBoliviaGtkSBFixedClass))
#define SINTIC_BOLIVIA_GTK_IS_SB_FIXED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_FIXED))
#define SINTIC_BOLIVIA_GTK_IS_SB_FIXED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_FIXED))
#define SINTIC_BOLIVIA_GTK_SB_FIXED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_FIXED, SinticBoliviaGtkSBFixedClass))

typedef struct _SinticBoliviaGtkSBFixed SinticBoliviaGtkSBFixed;
typedef struct _SinticBoliviaGtkSBFixedClass SinticBoliviaGtkSBFixedClass;
typedef struct _SinticBoliviaGtkSBFixedPrivate SinticBoliviaGtkSBFixedPrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_GTK_HELPER (sintic_bolivia_gtk_gtk_helper_get_type ())
#define SINTIC_BOLIVIA_GTK_GTK_HELPER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_GTK_HELPER, SinticBoliviaGtkGtkHelper))
#define SINTIC_BOLIVIA_GTK_GTK_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_GTK_HELPER, SinticBoliviaGtkGtkHelperClass))
#define SINTIC_BOLIVIA_GTK_IS_GTK_HELPER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_GTK_HELPER))
#define SINTIC_BOLIVIA_GTK_IS_GTK_HELPER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_GTK_HELPER))
#define SINTIC_BOLIVIA_GTK_GTK_HELPER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_GTK_HELPER, SinticBoliviaGtkGtkHelperClass))

typedef struct _SinticBoliviaGtkGtkHelper SinticBoliviaGtkGtkHelper;
typedef struct _SinticBoliviaGtkGtkHelperClass SinticBoliviaGtkGtkHelperClass;
typedef struct _SinticBoliviaGtkGtkHelperPrivate SinticBoliviaGtkGtkHelperPrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_SB_GTK_MODULE (sintic_bolivia_gtk_sb_gtk_module_get_type ())
#define SINTIC_BOLIVIA_GTK_SB_GTK_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_GTK_MODULE, SinticBoliviaGtkSBGtkModule))
#define SINTIC_BOLIVIA_GTK_SB_GTK_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_GTK_MODULE, SinticBoliviaGtkSBGtkModuleClass))
#define SINTIC_BOLIVIA_GTK_IS_SB_GTK_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_GTK_MODULE))
#define SINTIC_BOLIVIA_GTK_IS_SB_GTK_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_GTK_MODULE))
#define SINTIC_BOLIVIA_GTK_SB_GTK_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_GTK_MODULE, SinticBoliviaGtkSBGtkModuleClass))

typedef struct _SinticBoliviaGtkSBGtkModule SinticBoliviaGtkSBGtkModule;
typedef struct _SinticBoliviaGtkSBGtkModuleClass SinticBoliviaGtkSBGtkModuleClass;
typedef struct _SinticBoliviaGtkSBGtkModulePrivate SinticBoliviaGtkSBGtkModulePrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_INFO_DIALOG (sintic_bolivia_gtk_info_dialog_get_type ())
#define SINTIC_BOLIVIA_GTK_INFO_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_INFO_DIALOG, SinticBoliviaGtkInfoDialog))
#define SINTIC_BOLIVIA_GTK_INFO_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_INFO_DIALOG, SinticBoliviaGtkInfoDialogClass))
#define SINTIC_BOLIVIA_GTK_IS_INFO_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_INFO_DIALOG))
#define SINTIC_BOLIVIA_GTK_IS_INFO_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_INFO_DIALOG))
#define SINTIC_BOLIVIA_GTK_INFO_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_INFO_DIALOG, SinticBoliviaGtkInfoDialogClass))

typedef struct _SinticBoliviaGtkInfoDialog SinticBoliviaGtkInfoDialog;
typedef struct _SinticBoliviaGtkInfoDialogClass SinticBoliviaGtkInfoDialogClass;
typedef struct _SinticBoliviaGtkInfoDialogPrivate SinticBoliviaGtkInfoDialogPrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_SB_DATE_PICKER (sintic_bolivia_gtk_sb_date_picker_get_type ())
#define SINTIC_BOLIVIA_GTK_SB_DATE_PICKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_DATE_PICKER, SinticBoliviaGtkSBDatePicker))
#define SINTIC_BOLIVIA_GTK_SB_DATE_PICKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_DATE_PICKER, SinticBoliviaGtkSBDatePickerClass))
#define SINTIC_BOLIVIA_GTK_IS_SB_DATE_PICKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_DATE_PICKER))
#define SINTIC_BOLIVIA_GTK_IS_SB_DATE_PICKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_DATE_PICKER))
#define SINTIC_BOLIVIA_GTK_SB_DATE_PICKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_DATE_PICKER, SinticBoliviaGtkSBDatePickerClass))

typedef struct _SinticBoliviaGtkSBDatePicker SinticBoliviaGtkSBDatePicker;
typedef struct _SinticBoliviaGtkSBDatePickerClass SinticBoliviaGtkSBDatePickerClass;
typedef struct _SinticBoliviaGtkSBDatePickerPrivate SinticBoliviaGtkSBDatePickerPrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_TAG (sintic_bolivia_gtk_tag_get_type ())
#define SINTIC_BOLIVIA_GTK_TAG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_TAG, SinticBoliviaGtkTag))
#define SINTIC_BOLIVIA_GTK_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_TAG, SinticBoliviaGtkTagClass))
#define SINTIC_BOLIVIA_GTK_IS_TAG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_TAG))
#define SINTIC_BOLIVIA_GTK_IS_TAG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_TAG))
#define SINTIC_BOLIVIA_GTK_TAG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_TAG, SinticBoliviaGtkTagClass))

typedef struct _SinticBoliviaGtkTag SinticBoliviaGtkTag;
typedef struct _SinticBoliviaGtkTagClass SinticBoliviaGtkTagClass;
typedef struct _SinticBoliviaGtkTagPrivate SinticBoliviaGtkTagPrivate;

#define SINTIC_BOLIVIA_GTK_TYPE_SB_PRINT_PREVIEW (sintic_bolivia_gtk_sb_print_preview_get_type ())
#define SINTIC_BOLIVIA_GTK_SB_PRINT_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_PRINT_PREVIEW, SinticBoliviaGtkSBPrintPreview))
#define SINTIC_BOLIVIA_GTK_SB_PRINT_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_PRINT_PREVIEW, SinticBoliviaGtkSBPrintPreviewClass))
#define SINTIC_BOLIVIA_GTK_IS_SB_PRINT_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_PRINT_PREVIEW))
#define SINTIC_BOLIVIA_GTK_IS_SB_PRINT_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SINTIC_BOLIVIA_GTK_TYPE_SB_PRINT_PREVIEW))
#define SINTIC_BOLIVIA_GTK_SB_PRINT_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SINTIC_BOLIVIA_GTK_TYPE_SB_PRINT_PREVIEW, SinticBoliviaGtkSBPrintPreviewClass))

typedef struct _SinticBoliviaGtkSBPrintPreview SinticBoliviaGtkSBPrintPreview;
typedef struct _SinticBoliviaGtkSBPrintPreviewClass SinticBoliviaGtkSBPrintPreviewClass;
typedef struct _SinticBoliviaGtkSBPrintPreviewPrivate SinticBoliviaGtkSBPrintPreviewPrivate;

struct _SinticBoliviaGtkDbTableTreeView {
	GtkTreeView parent_instance;
	SinticBoliviaGtkDbTableTreeViewPrivate * priv;
	SinticBoliviaDatabaseSBDatabase* dbh;
	gchar* dbTable;
	gchar** tableColumns;
	gint tableColumns_length1;
	gchar** treeviewColumns;
	gint treeviewColumns_length1;
	gchar* query;
};

struct _SinticBoliviaGtkDbTableTreeViewClass {
	GtkTreeViewClass parent_class;
};

struct _SinticBoliviaGtkSBFixed {
	GtkFixed parent_instance;
	SinticBoliviaGtkSBFixedPrivate * priv;
	gint FixedWidth;
	gint width;
	gint X;
	gint Y;
	gint Margin;
	gint WidgetWidth;
	gint WidgetHeight;
	gint totalColumns;
	gint currentColumn;
};

struct _SinticBoliviaGtkSBFixedClass {
	GtkFixedClass parent_class;
};

struct _SinticBoliviaGtkGtkHelper {
	GObject parent_instance;
	SinticBoliviaGtkGtkHelperPrivate * priv;
};

struct _SinticBoliviaGtkGtkHelperClass {
	GObjectClass parent_class;
};

struct _SinticBoliviaGtkSBGtkModule {
	SinticBoliviaSBModule parent_instance;
	SinticBoliviaGtkSBGtkModulePrivate * priv;
	gchar* _moduleId;
	gchar* _name;
	gchar* _description;
	gchar* _author;
	gdouble _version;
	gchar* resourceFile;
	gchar* resourceNs;
	GResource* res_data;
};

struct _SinticBoliviaGtkSBGtkModuleClass {
	SinticBoliviaSBModuleClass parent_class;
};

struct _SinticBoliviaGtkInfoDialog {
	GtkDialog parent_instance;
	SinticBoliviaGtkInfoDialogPrivate * priv;
	gchar* dlgType;
	GtkEventBox* boxHeader;
};

struct _SinticBoliviaGtkInfoDialogClass {
	GtkDialogClass parent_class;
};

struct _SinticBoliviaGtkSBDatePicker {
	GtkFixed parent_instance;
	SinticBoliviaGtkSBDatePickerPrivate * priv;
	GtkEntry* entryDate;
	GtkCalendar* calendar;
	GtkDialog* popup;
};

struct _SinticBoliviaGtkSBDatePickerClass {
	GtkFixedClass parent_class;
};

struct _SinticBoliviaGtkTag {
	GtkFixed parent_instance;
	SinticBoliviaGtkTagPrivate * priv;
	GtkLabel* label1;
	GtkButton* button1;
};

struct _SinticBoliviaGtkTagClass {
	GtkFixedClass parent_class;
};

struct _SinticBoliviaGtkSBPrintPreview {
	GtkBox parent_instance;
	SinticBoliviaGtkSBPrintPreviewPrivate * priv;
	gdouble _ZOOM_IN_FACTOR;
	gdouble _ZOOM_OUT_FACTOR;
	GtkPrintOperation* _operation;
	GtkPrintContext* _context;
	GtkPrintOperationPreview* _operationPreview;
	GtkPageSetup* _pageSetup;
	GtkLayout* _layout;
	GtkScrolledWindow* _scrolledWindow;
	GtkToolButton* _next;
	GtkToolButton* _prev;
	GtkToolItem* _multi;
	GtkToolItem* _zoomOne;
	GtkToolItem* _zoomFit;
	GtkToolButton* _zoomIn;
	GtkToolButton* _zoomOut;
	GtkToolButton* _buttonPrint;
	GtkEntry* _pageEntry;
	GtkLabel* _labelLastPage;
	gdouble _paperWidth;
	gdouble _paperHeight;
	gdouble _pixelsWidth;
	gdouble _pixelsHeight;
	gdouble _dpi;
	gdouble _scale;
	gint _PAGE_PAD;
	gint _tile_w;
	gint _tile_h;
	gint _rows;
	gint _cols;
	guint _n_pages;
	guint _cur_page;
	gdouble _dpi_x;
	gdouble _dpi_y;
	guint TotalPages;
	guint CurrentPage;
};

struct _SinticBoliviaGtkSBPrintPreviewClass {
	GtkBoxClass parent_class;
};

VALA_EXTERN GType sintic_bolivia_gtk_db_table_tree_view_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkDbTableTreeView, g_object_unref)
VALA_EXTERN SinticBoliviaGtkDbTableTreeView* sintic_bolivia_gtk_db_table_tree_view_new (const gchar* db_table,
                                                                            gchar** cols,
                                                                            gint cols_length1,
                                                                            SinticBoliviaDatabaseSBDatabase* _dbh);
VALA_EXTERN SinticBoliviaGtkDbTableTreeView* sintic_bolivia_gtk_db_table_tree_view_construct (GType object_type,
                                                                                  const gchar* db_table,
                                                                                  gchar** cols,
                                                                                  gint cols_length1,
                                                                                  SinticBoliviaDatabaseSBDatabase* _dbh);
VALA_EXTERN void sintic_bolivia_gtk_db_table_tree_view_ParseColumns (SinticBoliviaGtkDbTableTreeView* self,
                                                         gchar** cols,
                                                         gint cols_length1);
VALA_EXTERN void sintic_bolivia_gtk_db_table_tree_view_BuildQuery (SinticBoliviaGtkDbTableTreeView* self);
VALA_EXTERN void sintic_bolivia_gtk_db_table_tree_view_Build (SinticBoliviaGtkDbTableTreeView* self);
VALA_EXTERN void sintic_bolivia_gtk_db_table_tree_view_Bind (SinticBoliviaGtkDbTableTreeView* self);
VALA_EXTERN GType sintic_bolivia_gtk_sb_fixed_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkSBFixed, g_object_unref)
VALA_EXTERN SinticBoliviaGtkSBFixed* sintic_bolivia_gtk_sb_fixed_new (void);
VALA_EXTERN SinticBoliviaGtkSBFixed* sintic_bolivia_gtk_sb_fixed_construct (GType object_type);
VALA_EXTERN void sintic_bolivia_gtk_sb_fixed_Build (SinticBoliviaGtkSBFixed* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_fixed_SetEvents (SinticBoliviaGtkSBFixed* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_fixed_SetWidgetSize (SinticBoliviaGtkSBFixed* self,
                                                gint width,
                                                gint height);
VALA_EXTERN void sintic_bolivia_gtk_sb_fixed_AddWidget (SinticBoliviaGtkSBFixed* self,
                                            GtkWidget* w);
VALA_EXTERN gint sintic_bolivia_gtk_sb_fixed_get_Width (SinticBoliviaGtkSBFixed* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_fixed_set_Width (SinticBoliviaGtkSBFixed* self,
                                            gint value);
VALA_EXTERN GType sintic_bolivia_gtk_gtk_helper_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkGtkHelper, g_object_unref)
VALA_EXTERN GtkBuilder* sintic_bolivia_gtk_gtk_helper_GetGladeUI (const gchar* glade_file);
VALA_EXTERN GdkPixbuf* sintic_bolivia_gtk_gtk_helper_GetPixbuf (const gchar* file,
                                                    gint width,
                                                    gint height);
VALA_EXTERN void sintic_bolivia_gtk_gtk_helper_BuildTreeViewColumns (gchar** cols,
                                                         gint cols_length1,
                                                         gint cols_length2,
                                                         GtkTreeView** treeview);
VALA_EXTERN GResource* sintic_bolivia_gtk_gtk_helper_LoadResource (const gchar* resource_file);
VALA_EXTERN GInputStream* sintic_bolivia_gtk_gtk_helper_GetInputStreamFromResource (GResource* res,
                                                                        const gchar* file);
VALA_EXTERN GtkBuilder* sintic_bolivia_gtk_gtk_helper_GetGladeUIFromResource (GResource* res,
                                                                  const gchar* glade_ui);
VALA_EXTERN SinticBoliviaGtkGtkHelper* sintic_bolivia_gtk_gtk_helper_new (void);
VALA_EXTERN SinticBoliviaGtkGtkHelper* sintic_bolivia_gtk_gtk_helper_construct (GType object_type);
VALA_EXTERN GType sintic_bolivia_gtk_sb_gtk_module_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkSBGtkModule, g_object_unref)
VALA_EXTERN void sintic_bolivia_gtk_sb_gtk_module_LoadResources (SinticBoliviaGtkSBGtkModule* self);
VALA_EXTERN GtkBuilder* sintic_bolivia_gtk_sb_gtk_module_GetGladeUi (SinticBoliviaGtkSBGtkModule* self,
                                                         const gchar* ui_file,
                                                         const gchar* t_domain);
VALA_EXTERN GInputStream* sintic_bolivia_gtk_sb_gtk_module_GetInputStream (SinticBoliviaGtkSBGtkModule* self,
                                                               const gchar* file);
VALA_EXTERN GdkPixbuf* sintic_bolivia_gtk_sb_gtk_module_GetPixbuf (SinticBoliviaGtkSBGtkModule* self,
                                                       const gchar* image,
                                                       gint width,
                                                       gint height);
VALA_EXTERN gchar** sintic_bolivia_gtk_sb_gtk_module_GetSQLFromResource (SinticBoliviaGtkSBGtkModule* self,
                                                             const gchar* sql_file,
                                                             gint* result_length1);
VALA_EXTERN SinticBoliviaGtkSBGtkModule* sintic_bolivia_gtk_sb_gtk_module_construct (GType object_type);
VALA_EXTERN GType sintic_bolivia_gtk_info_dialog_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkInfoDialog, g_object_unref)
VALA_EXTERN SinticBoliviaGtkInfoDialog* sintic_bolivia_gtk_info_dialog_new (const gchar* type);
VALA_EXTERN SinticBoliviaGtkInfoDialog* sintic_bolivia_gtk_info_dialog_construct (GType object_type,
                                                                      const gchar* type);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_Build (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_SetEvents (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_OnButtonCloseClicked (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN const gchar* sintic_bolivia_gtk_info_dialog_get_Title (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_set_Title (SinticBoliviaGtkInfoDialog* self,
                                               const gchar* value);
VALA_EXTERN const gchar* sintic_bolivia_gtk_info_dialog_get_Message (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_set_Message (SinticBoliviaGtkInfoDialog* self,
                                                 const gchar* value);
VALA_EXTERN GtkLabel* sintic_bolivia_gtk_info_dialog_get_LabelTitle (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_set_LabelTitle (SinticBoliviaGtkInfoDialog* self,
                                                    GtkLabel* value);
VALA_EXTERN GtkLabel* sintic_bolivia_gtk_info_dialog_get_LabelMessage (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_set_LabelMessage (SinticBoliviaGtkInfoDialog* self,
                                                      GtkLabel* value);
VALA_EXTERN GtkButton* sintic_bolivia_gtk_info_dialog_get_ButtonClose (SinticBoliviaGtkInfoDialog* self);
VALA_EXTERN void sintic_bolivia_gtk_info_dialog_set_ButtonClose (SinticBoliviaGtkInfoDialog* self,
                                                     GtkButton* value);
VALA_EXTERN GType sintic_bolivia_gtk_sb_date_picker_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkSBDatePicker, g_object_unref)
VALA_EXTERN SinticBoliviaGtkSBDatePicker* sintic_bolivia_gtk_sb_date_picker_new (void);
VALA_EXTERN SinticBoliviaGtkSBDatePicker* sintic_bolivia_gtk_sb_date_picker_construct (GType object_type);
VALA_EXTERN void sintic_bolivia_gtk_sb_date_picker_SetEvents (SinticBoliviaGtkSBDatePicker* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_date_picker_OnButtonSelectDateClicked (SinticBoliviaGtkSBDatePicker* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_date_picker_OnDateSelected (SinticBoliviaGtkSBDatePicker* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_date_picker_OnDaySelectedDoubleClick (SinticBoliviaGtkSBDatePicker* self);
VALA_EXTERN const gchar* sintic_bolivia_gtk_sb_date_picker_get_DateString (SinticBoliviaGtkSBDatePicker* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_date_picker_set_DateString (SinticBoliviaGtkSBDatePicker* self,
                                                       const gchar* value);
VALA_EXTERN void sintic_bolivia_gtk_sb_date_picker_set_Icon (SinticBoliviaGtkSBDatePicker* self,
                                                 GdkPixbuf* value);
VALA_EXTERN GType sintic_bolivia_gtk_tag_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkTag, g_object_unref)
VALA_EXTERN SinticBoliviaGtkTag* sintic_bolivia_gtk_tag_new (void);
VALA_EXTERN SinticBoliviaGtkTag* sintic_bolivia_gtk_tag_construct (GType object_type);
VALA_EXTERN void sintic_bolivia_gtk_tag_SetEvents (SinticBoliviaGtkTag* self);
VALA_EXTERN void sintic_bolivia_gtk_tag_OnButtonRemoveClicked (SinticBoliviaGtkTag* self);
VALA_EXTERN const gchar* sintic_bolivia_gtk_tag_get_Text (SinticBoliviaGtkTag* self);
VALA_EXTERN void sintic_bolivia_gtk_tag_set_Text (SinticBoliviaGtkTag* self,
                                      const gchar* value);
VALA_EXTERN GType sintic_bolivia_gtk_sb_print_preview_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (SinticBoliviaGtkSBPrintPreview, g_object_unref)
VALA_EXTERN SinticBoliviaGtkSBPrintPreview* sintic_bolivia_gtk_sb_print_preview_new (GtkPrintOperation* _op,
                                                                         GtkPrintOperationPreview* _op_preview,
                                                                         GtkPrintContext* _context);
VALA_EXTERN SinticBoliviaGtkSBPrintPreview* sintic_bolivia_gtk_sb_print_preview_construct (GType object_type,
                                                                               GtkPrintOperation* _op,
                                                                               GtkPrintOperationPreview* _op_preview,
                                                                               GtkPrintContext* _context);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_buildWidget (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN cairo_status_t sintic_bolivia_gtk_sb_print_preview_writeFunc (SinticBoliviaGtkSBPrintPreview* self,
                                                              guchar* data,
                                                              gint data_length1);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_setEvents (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_onPreviewReady (SinticBoliviaGtkSBPrintPreview* self,
                                                         GtkPrintContext* context);
VALA_EXTERN gboolean sintic_bolivia_gtk_sb_print_preview_OnLayoutDraw (SinticBoliviaGtkSBPrintPreview* self,
                                                           cairo_t* context);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_buildPageFrame (SinticBoliviaGtkSBPrintPreview* self,
                                                         cairo_t** context,
                                                         gdouble width,
                                                         gdouble height);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_drawPageContent (SinticBoliviaGtkSBPrintPreview* self,
                                                          cairo_t* context,
                                                          gint page_number);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_onGotPageSize (SinticBoliviaGtkSBPrintPreview* self,
                                                        GtkPrintContext* context,
                                                        GtkPageSetup* page_setup);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_updatePaperSize (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN gdouble sintic_bolivia_gtk_sb_print_preview_getScreenDpi (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_setZoomFactor (SinticBoliviaGtkSBPrintPreview* self,
                                                        gdouble zoom);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_updateTileSize (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_updateLayoutSize (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN gdouble sintic_bolivia_gtk_sb_print_preview_getPaperWidth (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN gdouble sintic_bolivia_gtk_sb_print_preview_getPaperHeight (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_goToPage (SinticBoliviaGtkSBPrintPreview* self,
                                                   gint page);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_OnZoomInButtonClicked (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_OnZoomOutButtonClicked (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_OnPrevButtonClicked (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN void sintic_bolivia_gtk_sb_print_preview_OnNextButtonClicked (SinticBoliviaGtkSBPrintPreview* self);
VALA_EXTERN cairo_t* sintic_bolivia_gtk_sb_print_preview_get_CairoContext (SinticBoliviaGtkSBPrintPreview* self);

G_END_DECLS

#endif
